### ISSUE TITLE
Package-qualified imports

### ISSUE THREAD

**Issue by jvmap** [yav/graphmod#1]
Hi,

Thanks for this excellent program. One issue I ran into: it appears that graphmod cannot deal with the recent GHC feature "package-qualified imports".

http://www.haskell.org/ghc/docs/latest/html/users_guide/syntax-extns.html (section 7.3.18)

Only imports above the first package-qualified import are taken into account when the dependency graph is generated, any remaining imports seem to be ignored. Maybe graphmod could deal with this case more gracefully?

Regards,
Jeroen

**Comment by yav** [comment]
This should be fixed now.
