### ISSUE TITLE
Optionally merge directory name and package

### ISSUE THREAD

**Issue by Ongy** [yav/graphmod#10]
When I create a graph with `graphmod` and have modules like
> System.Linux.Netlink
> System.Linux.Netlink.Constants
> System.Linux.Netlink.Helpers
the latter two are clustered, but the first one looks rather unrelated in the `System.Linux` directory.
It would be nice to have an option to merge the module name with directoy name. So that the node for `System.Linux.Netlink` is where currently the directory name is.

Image created with `graphmod -p | dot -Tpng`
![example](http://i.imgur.com/tBXOtiy.png)

**Comment by yav** [comment]
Hi, I just pushed a version that draws things differently.  Could you give it a try and see if it works better?

It draws modules that have the same name as a cluster withing the cluster, but they have a think border.  Other modules have no border, so you can tell them apart.  Also, the modules in each cluster now have a different color, while the nesting of the clusters is marked with shades of gray.

Let me know what you think.

**Comment by Ongy** [comment]
Looks good to me.

**Comment by yav** [comment]
Great.  I've released it on Hackage as version 1.3.
