### ISSUE TITLE
Request: output dependencies in csv or similar format for processing with other tools

### ISSUE THREAD

**Issue by ifigueroap** [yav/graphmod#11]
Hi, I recently found out about graphmod, as I'm looking to compute the static dependencies between Haskell files. However, the dot output is too specific, and although I want to produce graphics, I need to do some preprocessing first.

Hence, I would like to request a feature, that perhaps is simple from the point of view of the original developer! Is it possible to add a flag to output a CSV file, such as:

```
file;dependsOn;sourceImport
fully/qualified/path/to/A.hs; fully/qualified/other/path/to/B.hs; No
fully/qualified/path/to/C.hs; fully/qualified/other/path/to/D.hs; Yes
```

???
If not possible I would thank any pointers to where/how should I work in order to make this work...

Thanks!

**Comment by yav** [comment]
This wouldn't be hard to do, but depending on what you are planning to do, `graphmod` might not be the best option---it uses a bunch of heuristics to find files and to deal with pragmatic things such as CPP.

It may be more reliable to use `ghc -ddump-minimal-imports` instead...   In fact, I've been wondering if I should make `graphmod` use that too.
