### ISSUE TITLE
Causes dot to crash on diagram generated for cardano-sl

### ISSUE THREAD

**Issue by Pastafarianist** [yav/graphmod#18]
Steps to reproduce:

```
stack install graphmod
git clone https://github.com/input-output-hk/cardano-sl.git
cd cardano-sl
find  -name '*.hs' | xargs graphmod -q > modules.dot
dot -Tpdf modules.dot -o modules.pdf 2>modules.err
```

Observe segfault. `modules.err` will contain [this](https://gist.github.com/Pastafarianist/bbcb72e8e3646317608d05a76ba61ae2).

```
$ dot -V
dot - graphviz version 2.38.0 (20140413.2041)
```

This is most likely a bug in `graphviz`, but I'm creating a bug report here to let you know of this issue. The `graphviz` issue is [here](https://gitlab.com/graphviz/graphviz/issues/1329).

**Comment by yav** [comment]
Yeah, I've encountered this also.  It seems like it's been a long standing bug in `graphviz`.   It doesn't seem to happen with version `2.40.1`, which you can get by downloading the source code from the `graphviz` web-site and building it.
