### ISSUE TITLE
Add cabal support

### ISSUE THREAD

**Issue by chamini2** [yav/graphmod#2]
I must say, great project.

One thing that may be added is to make it first check if is in a directory with a `*.cabal` file, if there is such file, it should check the `hs-source-dirs` attribute to look for files in said directories.

It comes down to looking for that attribute and adding it to the command with the `-i <dir>` flag that `graphmod` already has.

**Comment by yav** [comment]
So I know it's been a few years, but I finally got around to implementing something like this.  If you are still interested, would you give the current implementation a go.

The cabal support is not very configurable at the moment.  The behavior is that if there is a .cabal file in the current directory, we will parse it and add all libraries and executables as roots for the graph drawing.   We also add `hs-source-dirs` to the search path.

**Comment by chamini2** [comment]
Hey @yav, that is great to hear, unfortunately I've moved away from the project in which I wanted this feature to be added, so testing it would be impossible for me right now. Thanks for the message anyways.
