### ISSUE TITLE
Help! Can't get to work...

### ISSUE THREAD

**Issue by mouse07410** [yav/graphmod#26]
MacOS Mojave 10.14.4, Xcode-10.2.1, ghcup-installed toolchain GHC-8.6.4. 

Installation of `graphmod` and `xdot` via Cabal succeeded, however the executable `xdot` is nowhere to be found.

How do I actually display the graph? I tried this from your wiki:
```
find src -name '*.hs' | xargs graphmod -q | xdot -
```

Thanks for any help you can offer.

**Comment by abailly** [comment]
Do not use `xdot` but use `dot`, installed with `brew install graphviz`

**Comment by yav** [comment]
Indeed, `graphmod` produces `graphviz` graphs, and there are quite a few different tools that can render them.  You can use `dot` to generate a `pdf` like this:
```
graphmod Main.hs | dot -T pdf -o module-graph.pdf
```
The result will be in a file called `module-graph.pdf`
