### ISSUE TITLE
Export functionality as a dummy library

### ISSUE THREAD

**Issue by Fuuzetsu** [yav/graphmod#31]
We have a Haskell program that currently invokes `graphmod` as part of its functionality. We have to ensure `graphmod` is installed, pass in the right flags and so on.

It would be great if `graphmod` had a `library` section. This would allow us to add it to the cabal dependencies and just let cabal deal with building it.

This library doesn't even have to be pretty/nice: just blindly exporting everything is cool.

It would even be an improvement if it only exported `run :: [String] -> IO ()` that allows us to pass `args`. Some packages that do this are for example [`weeder`](https://hackage.haskell.org/package/weeder-1.0.9/docs/Weeder.html), another is [`doctest`](https://hackage.haskell.org/package/doctest-0.17). `hlint` and other tools also expose part of their functionality as libraries and it helps us a great deal with not having to think about provisioning these ahead of time.

**Comment by yav** [comment]
Seems reasonable, would you mind making a pull request?

**Comment by Fuuzetsu** [comment]
MR at https://github.com/yav/graphmod/pull/33

**Comment by mitchellwrosen** [comment]
Ping! :)
