### ISSUE TITLE
Allow to treat  `{-# SOURCE #-}`-imports differently

### ISSUE THREAD

**Issue by hvr** [yav/graphmod#4]
It may be useful to be able to optionally ignore `{-# SOURCE #-}` imports, in order to recover a cycle-free import tree-graph (on which the transitive reduction (that's what `--prunde-edges` does, doesn't it?) is unique), and/or add the `{-# SOURCE #-}`-edges afterwards to the graph with a different drawing style (dashed/colored/whatever).

This depends on the lexer being able to tokenize `{-# SOURCE #-}` (which it currently doesn't)

I think this would be useful to have in order to better visualize packages with import-cycles.

**Comment by yav** [comment]
Hi,
sorry this took so long!  I think I implemented this, give it a go!
